spring.application.name=keystone-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/keystone_db
spring.datasource.username=postgres
spring.datasource.password=Puneeth@1767

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=keystoneSecretKeyForZidioInternshipProjectMustBeLongEnough123456
jwt.expiration=86400000